export = {
    customSyntax: require('postcss-scss'),
    plugins: [
        'stylelint-scss',
        'stylelint-codeguide',
    ],
    rules: {
        'at-rule-no-unknown': null,
        'codeguide/block-closing-brace-empty-line-before': 'never',
        'codeguide/block-closing-brace-newline-after': 'always',
        'codeguide/block-closing-brace-newline-before': 'always',
        'codeguide/block-closing-brace-space-after': 'never-single-line',
        'codeguide/block-closing-brace-space-before': 'never-single-line',
        'block-no-empty': true,
        'codeguide/block-opening-brace-newline-after': 'always-multi-line',
        'codeguide/block-opening-brace-newline-before': 'always-single-line',
        'codeguide/block-opening-brace-space-after': 'always-single-line',
        'codeguide/block-opening-brace-space-before': 'always',
        'codeguide/color-hex-case': 'lower',
        'color-hex-length': 'long',
        'color-no-invalid-hex': true,
        'comment-empty-line-before': 'never',
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-empty-line-before': 'never',
        'font-family-name-quotes': 'always-unless-keyword',
        'font-family-no-duplicate-names': true,
        'font-family-no-missing-generic-family-keyword': true,
        'font-weight-notation': 'named-where-possible',
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-url-quotes': 'always',
        'codeguide/indentation': 4,
        'keyframe-declaration-no-important': true,
        'length-zero-no-unit': true,
        'codeguide/linebreaks': 'unix',
        'codeguide/max-empty-lines': 1,
        'media-feature-name-no-unknown': true,
        'codeguide/no-empty-first-line': true,
        'no-empty-source': null,
        'codeguide/no-eol-whitespace': true,
        'codeguide/no-extra-semicolons': true,
        'no-invalid-position-at-import-rule': [
            true,
            {
                ignoreAtRules: [
                    'use'
                ]
            }
        ],
        'codeguide/no-missing-end-of-source-newline': true,
        'codeguide/number-leading-zero': 'always',
        'number-max-precision': 3,
        'codeguide/number-no-trailing-zeros': true,
        'codeguide/property-case': 'lower',
        'property-no-unknown': true,
        'property-no-vendor-prefix': null,
        'scss/at-extend-no-missing-placeholder': true,
        'scss/at-if-no-null': true,
        'scss/at-import-partial-extension': 'always',
        'scss/at-rule-no-unknown': true,
        'scss/comment-no-empty': true,
        'scss/declaration-nested-properties-no-divided-groups': true,
        'scss/dollar-variable-no-missing-interpolation': true,
        'scss/function-quote-no-quoted-strings-inside': true,
        'scss/function-unquote-no-unquoted-strings-inside': true,
        'scss/load-no-partial-leading-underscore': true,
        'scss/no-duplicate-mixins': true,
        'scss/no-global-function-names': true,
        'scss/operator-no-newline-after': true,
        'scss/operator-no-newline-before': true,
        'scss/operator-no-unspaced': true,
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-element-no-unknown': [
            true,
            {
                ignorePseudoElements: [
                    'ng-deep'
                ]
            }
        ],
        'selector-type-no-unknown': null,
        'string-no-newline': true,
        'codeguide/string-quotes': 'double',
        'codeguide/unit-case': 'lower',
        'unit-no-unknown': true,
        'value-keyword-case': 'lower',
        'value-no-vendor-prefix': null
    },
};
