name: Publish to npm on a release

on:
  push:
    branches:
      - master
    paths:
      - src/**
  release:
    types:
      - published

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run amend
        env:
          GITHUB_IS_PRERELEASE: ${{ github.event.release.prerelease }}
      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GRAN_TOKEN }}
